FRONTEND-55. Feature: added interceptor for 400 & 409 error catching.
MangoInstantMessenger/MangoMessengerAPI pull request #467
Opened 2023-03-23 19:32 UTC by Khachatur-Khachatryan

Additions: 
1. Added ErrorInterceptor that cathces 409 and 400 responses and alert they error details
2. Added condition in UpdateUserAccountInfoCommandHandler.cs that checks if thereis such username in DB. If there is - return 409 error
3. Removed ErrorNotificationService
4. Removed console logs in contacts component (in loadContacts)
5. Now in 'subscribe' method passes only 'next' argument, without 'error'. For example see create group component.
6. Removed try-catch statement in register component (in onRegisterClick)
7. Removed alerts in settings component (in onSaveChangesAccountInfoClick, onSavePersonalInformationClick, onSaveProfilePictureClick, onSaveChangesChangePasswordClick)
8. Updated validation service

2023-03-23 20:12 UTC, kolosovpetro requested changes

2023-03-23 20:12 UTC, kolosovpetro commented on MangoAPI.Client/src/app/components/settings/settings.component.ts
> -      this._errorNotificationService.notifyOnError(e);
This catch block leads to bug, because error already caught in interceptor, so that Image won't be cleared

2023-03-23 20:12 UTC, kolosovpetro commented on MangoAPI.Client/src/app/components/settings/settings.component.ts
>      this.clearChangePasswordCommand();
If there is an error -- then `this.clearChangePasswordCommand();` won't be called and data won't be cleared

2023-03-23 20:12 UTC, kolosovpetro commented on MangoAPI.Client/src/app/components/login/login.component.ts
> -        },
Rewrite whole login action using async/await

2023-03-23 20:12 UTC, kolosovpetro commented on MangoAPI.Client/src/app/components/create-group/create-group.component.ts
> -          this._errorNotificationService.notifyOnError(error);
Rewrite whole create group component using async/await

2023-03-23 20:22 UTC, kolosovpetro commented
TODO:

- Remove every implementation of `ngOnDestroy` -- it is redundant now

2023-04-01 13:15 UTC, kolosovpetro approved these changes
Looks good to me, thanks

2023-04-02 15:27 UTC, Khachatur-Khachatryan commented
> Looks good to me, thanks

Your welcome!

2023-04-02 19:55 UTC, merged